profile_pin:
  target: dev
  outputs:
    dev:
      type: snowflake
      ######## Please replace with your Snowflake account name
      ######## for example sg_demo.ap-southeast-1
      account: gf95582.eu-west-1
      #account: snztwuw-ff95009
      #account: FF95009

      user: "{{ env_var('dbt_user') }}"
      ######## These environment variables dbt_user and dbt_password
      ######## are read from the variabls in Airflow which we will set later
      password: "{{ env_var('dbt_password') }}"

      role: DBT_DEV_ROLE
      database: DEMO_DBT
      warehouse: DBT_DEV_WH
      schema: PUBlIC
      threads: 200